# Generated by pymake version 0.4.4
# PyMake was written by Stephen Melinyshyn | github.com/Melinysh/PyMake

CXX := g++
CXXFLAGS := -Wall -g
PYMAKE_COMPILER := $(CXX)
PYMAKE_COMPILER_FLAGS := $(CXXFLAGS)
SOURCES := $(wildcard *.cc)
INSTALL_PATH := ~/bin/
TARGET := a.out
OBJS := $(patsubst %.cc, %.o, $(SOURCES))
all: $(TARGET)

$(TARGET): $(OBJS)

	$(PYMAKE_COMPILER) -o $(TARGET) $^

%.o: %.c
	$(PYMAKE_COMPILER) $< $(PYMAKE_COMPILER_FLAGS) -o $@

clean:
	-rm $(TARGET) $(OBJS)

run: all
	./$(TARGET)

install: $(TARGET)
	install $(TARGET) $(INSTALL_PATH)

uninstall:
	-rm $(INSTALL_PATH)/$(TARGET)
